# Chapter 2: Computing and Displaying data

## 2.1 Spherical Astronomy

### 2.1.1 Declination of the Sun
$$d = - \arcsin(\sin \epsilon_0 \cos (\frac{360}{365.24} \times (N + 10)))$$


In [2]:
# N is the difference of the days from first day of the year (1st jan)
# find the declination of the sun given N and the formula above

import math

N = 171 # day of the solstice 20th of June in 2020 which is 171 days away from 1st jan
omega = 2 * math.pi / 365.24 # angular velocity in radian/day same as 360/365.24
ecl = math.radians(23.44) #obliquity of the ecliptic 

# approximate expression of sun declination **refer to the formula above
delta = -math.asin( math.sin(ecl) * math.cos( omega * (N +10)))
print("declination of the sun is {:.2f} degrees".format(math.degrees(delta))) # here we need to convert the value from radian to degrees

declination of the sun is 23.43 degrees


#### compute the declination for several days, How?

In [4]:
# use numpy arrays
import numpy as np
N = np.array([79, 171, 265, 355]) # equinoxes and solstices in 2020
print(N)
print(N.size)
print(N.dtype)
print(N[1])
print(N[-3])

[ 79 171 265 355]
4
int32
171
171


In [6]:
# compute the declination of the sun for all given days at once
delta = -np.arcsin( math.sin(ecl) * np.cos( omega * (N +10)))
print(np.degrees(delta))

[ -0.9055077   23.43035419  -0.41950731 -23.43978827]


In [7]:
# breaking down the same code above, we get:
temp = N +10 # add 10 to each element in the array
print(temp)
print(temp.dtype)

temp = omega * temp # perform element-wise multiplication
print(temp)
print(temp.dtype)

temp = math.sin(ecl) * np.cos(temp)
print(temp)

delta = -np.arcsin(temp)
print(np.degrees(delta))

[ 89 181 275 365]
int32
[1.53105764 3.11372396 4.73079608 6.27905661]
float64
[ 0.01580343 -0.39763404  0.00732172  0.39778512]
[ -0.9055077   23.43035419  -0.41950731 -23.43978827]


In [8]:
# display elements in the array
for element in delta:
    print(" the declination is {:6.2f} degrees".format(math.degrees(element)))

 the declination is  -0.91 degrees
 the declination is  23.43 degrees
 the declination is  -0.42 degrees
 the declination is -23.44 degrees


In [9]:
# better way to display data
print("i    dat    delta {deg}")
for i, val in enumerate(delta):
    print("{1:d}    {2:3d}    {0:8.2f}".format(math.degrees(val), i, N[i]))

i    dat    delta {deg}
0     79       -0.91
1    171       23.43
2    265       -0.42
3    355      -23.44


In [10]:
# even better
print("dat    delta {deg}")
for row in zip(N,delta):
    print("{0:3d}    {1:8.2f}".format(row[0], math.degrees(row[1])))

dat    delta {deg}
 79       -0.91
171       23.43
265       -0.42
355      -23.44
